// Pure deterministic math for the Feature Engineering Craft guide. No React here.
//
// Honest-by-construction: every displayed number is computed from datasets
// generated by a seeded PRNG (mulberry32, literal seeds below). Every fit is an
// exact least-squares solve of the normal equations (X^T X) beta = X^T y via
// Gaussian elimination with partial pivoting. Nothing is precomputed or faked.

// ── Seeded PRNG ──────────────────────────────────────────────────────────────

/** mulberry32: deterministic stream in [0, 1), identical on server and client. */
export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function clamp(v: number, lo: number, hi: number): number {
  return Math.min(hi, Math.max(lo, v));
}

export function mean(xs: readonly number[]): number {
  if (xs.length === 0) return 0;
  return xs.reduce((a, b) => a + b, 0) / xs.length;
}

// ── Exact least squares via the normal equations ─────────────────────────────

export interface FitResult {
  beta: number[];
  predictions: number[];
  /** Root mean squared error of the fit on the data it was fit to. */
  rmse: number;
  /** 1 - SSE/SST with SST about the mean of y. */
  r2: number;
}

/**
 * Solves A x = b by Gaussian elimination with partial pivoting.
 * Returns null when A is (numerically) singular.
 */
export function solveLinearSystem(A: number[][], b: number[]): number[] | null {
  const n = A.length;
  const M = A.map((row, i) => [...row, b[i]]);
  for (let col = 0; col < n; col++) {
    let piv = col;
    for (let r = col + 1; r < n; r++) {
      if (Math.abs(M[r][col]) > Math.abs(M[piv][col])) piv = r;
    }
    if (Math.abs(M[piv][col]) < 1e-9) return null;
    const tmp = M[col];
    M[col] = M[piv];
    M[piv] = tmp;
    for (let r = 0; r < n; r++) {
      if (r === col) continue;
      const f = M[r][col] / M[col][col];
      for (let c = col; c <= n; c++) M[r][c] -= f * M[col][c];
    }
  }
  return M.map((row, i) => row[n] / M[i][i]);
}

/** Exact OLS: beta = (X^T X)^{-1} X^T y. Returns null if X^T X is singular. */
export function leastSquares(X: number[][], y: number[]): FitResult | null {
  const n = X.length;
  const p = X[0].length;
  const XtX: number[][] = Array.from({ length: p }, () => new Array<number>(p).fill(0));
  const Xty: number[] = new Array<number>(p).fill(0);
  for (let i = 0; i < n; i++) {
    for (let a = 0; a < p; a++) {
      Xty[a] += X[i][a] * y[i];
      for (let b = a; b < p; b++) XtX[a][b] += X[i][a] * X[i][b];
    }
  }
  for (let a = 0; a < p; a++) {
    for (let b = 0; b < a; b++) XtX[a][b] = XtX[b][a];
  }
  const beta = solveLinearSystem(XtX, Xty);
  if (!beta) return null;
  const predictions = X.map((row) => row.reduce((s, v, j) => s + v * beta[j], 0));
  const meanY = mean(y);
  let sse = 0;
  let sst = 0;
  for (let i = 0; i < n; i++) {
    sse += (y[i] - predictions[i]) ** 2;
    sst += (y[i] - meanY) ** 2;
  }
  return {
    beta,
    predictions,
    rmse: Math.sqrt(sse / n),
    r2: sst === 0 ? 0 : 1 - sse / sst,
  };
}

// ── Section 1: ad spend vs daily signups, one feature, five shapes ───────────

export interface AdPoint {
  /** Daily ad spend in dollars. */
  spend: number;
  /** Daily signups (the target). */
  signups: number;
}

export const AD_SEED = 20260716;
export const AD_N = 120;
export const AD_NOISE = 8;

/**
 * Diminishing-returns world: signups = 4 + 22 * ln(1 + spend / 50) + noise.
 * The log transform matches the generating shape; the square transform bends
 * the opposite way, so it must fit WORSE than the raw feature.
 */
export function generateAdData(): AdPoint[] {
  const rand = mulberry32(AD_SEED);
  const points: AdPoint[] = [];
  for (let i = 0; i < AD_N; i++) {
    const spend = 50 + rand() * 1950;
    const signal = 4 + 22 * Math.log(1 + spend / 50);
    const signups = clamp(signal + (rand() * 2 - 1) * AD_NOISE, 0.5, 200);
    points.push({ spend, signups });
  }
  return points.sort((a, b) => a.spend - b.spend);
}

export type TransformId = "raw" | "log" | "sqrt" | "square" | "bins";

export const TRANSFORM_ORDER: readonly TransformId[] = [
  "raw",
  "log",
  "sqrt",
  "square",
  "bins",
];

export interface TransformMeta {
  id: TransformId;
  label: string;
  formula: string;
  color: string;
  tagline: string;
}

export const TRANSFORM_META: Record<TransformId, TransformMeta> = {
  raw: {
    id: "raw",
    label: "Raw",
    formula: "x",
    color: "#94a3b8",
    tagline: "The column as it arrived. A straight line through a curved world.",
  },
  log: {
    id: "log",
    label: "Log",
    formula: "ln(1 + x)",
    color: "var(--color-success)",
    tagline: "Compresses the big values. The go-to move for diminishing returns.",
  },
  sqrt: {
    id: "sqrt",
    label: "Square root",
    formula: "sqrt(x)",
    color: "#3bb4a4",
    tagline: "A gentler compression than log. Often close, rarely identical.",
  },
  square: {
    id: "square",
    label: "Square",
    formula: "x^2",
    color: "#ef4444",
    tagline: "Bends the opposite way. Transforms are hypotheses, and hypotheses can be wrong.",
  },
  bins: {
    id: "bins",
    label: "Bins",
    formula: "quantile bins",
    color: "#a855f7",
    tagline: "No shape assumption at all: one mean per bin. Flexibility priced in parameters.",
  },
};

export const BIN_MIN = 3;
export const BIN_MAX = 10;
export const BIN_INITIAL = 5;

/** Applies a smooth (non-bin) transform to the raw feature. */
export function applyTransform(t: Exclude<TransformId, "bins">, x: number): number {
  switch (t) {
    case "raw":
      return x;
    case "log":
      return Math.log(1 + x);
    case "sqrt":
      return Math.sqrt(x);
    case "square":
      return x * x;
  }
}

/** Quantile bin edges (interior edges only) for the sorted spend values. */
export function quantileEdges(sortedX: readonly number[], bins: number): number[] {
  const edges: number[] = [];
  for (let b = 1; b < bins; b++) {
    const idx = Math.floor((b * sortedX.length) / bins);
    edges.push(sortedX[Math.min(idx, sortedX.length - 1)]);
  }
  return edges;
}

export function binIndex(x: number, edges: readonly number[]): number {
  let b = 0;
  while (b < edges.length && x >= edges[b]) b++;
  return b;
}

export interface TransformFit {
  id: TransformId;
  rmse: number;
  r2: number;
  /** Number of fitted parameters (for the bins honesty note). */
  params: number;
  /** Polyline of (spend, predicted signups) for drawing the fit. */
  curve: { x: number; y: number }[];
}

/**
 * Fits signups on the transformed spend by exact OLS and returns the error
 * plus a drawable fit curve. For "bins" the model is one mean per quantile
 * bin (one-hot bin membership, no intercept), drawn as a step function.
 */
export function computeTransformFit(
  data: readonly AdPoint[],
  id: TransformId,
  binCount: number
): TransformFit {
  const y = data.map((p) => p.signups);
  const xs = data.map((p) => p.spend);
  if (id === "bins") {
    const edges = quantileEdges(xs, binCount);
    const X = data.map((p) => {
      const row = new Array<number>(binCount).fill(0);
      row[binIndex(p.spend, edges)] = 1;
      return row;
    });
    const fit = leastSquares(X, y);
    if (!fit) return { id, rmse: 0, r2: 0, params: binCount, curve: [] };
    const minX = xs[0];
    const maxX = xs[xs.length - 1];
    const bounds = [minX, ...edges, maxX];
    const curve: { x: number; y: number }[] = [];
    for (let b = 0; b < binCount; b++) {
      curve.push({ x: bounds[b], y: fit.beta[b] });
      curve.push({ x: bounds[b + 1], y: fit.beta[b] });
    }
    return { id, rmse: fit.rmse, r2: fit.r2, params: binCount, curve };
  }
  const X = data.map((p) => [1, applyTransform(id, p.spend)]);
  const fit = leastSquares(X, y);
  if (!fit) return { id, rmse: 0, r2: 0, params: 2, curve: [] };
  const minX = xs[0];
  const maxX = xs[xs.length - 1];
  const STEPS = 60;
  const curve = Array.from({ length: STEPS + 1 }, (_, i) => {
    const x = minX + ((maxX - minX) * i) / STEPS;
    return { x, y: fit.beta[0] + fit.beta[1] * applyTransform(id, x) };
  });
  return { id, rmse: fit.rmse, r2: fit.r2, params: 2, curve };
}

// ── Section 2: delivery cost, where two features multiply ────────────────────

export interface Delivery {
  /** Distance in km. */
  distance: number;
  /** Weight in kg. */
  weight: number;
  /** Invoice total in dollars (the target). */
  cost: number;
}

export const DELIVERY_SEED = 20260717;
export const DELIVERY_N = 90;
export const DELIVERY_NOISE = 4;

/**
 * The courier charges partly per km-kg: cost has a distance * weight term, so
 * no additive model in distance and weight alone can express it.
 */
export function generateDeliveries(): Delivery[] {
  const rand = mulberry32(DELIVERY_SEED);
  const rows: Delivery[] = [];
  for (let i = 0; i < DELIVERY_N; i++) {
    const distance = 1 + rand() * 29;
    const weight = 0.5 + rand() * 19.5;
    const cost =
      5 + 0.9 * distance + 0.4 * weight + 0.11 * distance * weight + (rand() * 2 - 1) * DELIVERY_NOISE;
    rows.push({ distance, weight, cost });
  }
  return rows;
}

export interface InteractionFits {
  /** OLS of cost on [1, distance, weight]. */
  additive: FitResult;
  /** OLS of cost on [1, distance, weight, distance * weight]. */
  interaction: FitResult;
}

export function computeInteractionFits(rows: readonly Delivery[]): InteractionFits {
  const y = rows.map((r) => r.cost);
  const additive = leastSquares(
    rows.map((r) => [1, r.distance, r.weight]),
    y
  );
  const interaction = leastSquares(
    rows.map((r) => [1, r.distance, r.weight, r.distance * r.weight]),
    y
  );
  if (!additive || !interaction) {
    throw new Error("Normal equations unexpectedly singular on the fixed delivery dataset");
  }
  return { additive, interaction };
}

// ── Section 3: a datetime column expands into real features ─────────────────

export interface HourRow {
  /** Hours since Monday 00:00 of week 1 (the raw timestamp number). */
  t: number;
  /** Day of week, 0 = Monday .. 6 = Sunday. */
  dow: number;
  /** Hour of day, 0..23. */
  hour: number;
  /** Bike pickups in that hour (the target). */
  pickups: number;
}

export const HOURS_SEED = 20260718;
export const HOURS_DAYS = 14;
export const HOURS_N = HOURS_DAYS * 24;
export const HOURS_NOISE = 4;

function weekdayCurve(h: number): number {
  return (
    36 * Math.exp(-((h - 8.5) ** 2) / 9) +
    32 * Math.exp(-((h - 17.5) ** 2) / 10) +
    8 * Math.exp(-((h - 13) ** 2) / 12)
  );
}

function weekendCurve(h: number): number {
  return 26 * Math.exp(-((h - 14) ** 2) / 16);
}

/**
 * Two weeks of hourly bike-share pickups starting on a Monday at midnight.
 * Weekdays have commute peaks; weekends have one lazy midday hump.
 */
export function generateHourly(): HourRow[] {
  const rand = mulberry32(HOURS_SEED);
  const rows: HourRow[] = [];
  for (let t = 0; t < HOURS_N; t++) {
    const dow = Math.floor(t / 24) % 7;
    const hour = t % 24;
    const isWeekend = dow >= 5;
    const signal = 5 + (isWeekend ? weekendCurve(hour) : weekdayCurve(hour));
    const pickups = Math.max(0, signal + (rand() * 2 - 1) * HOURS_NOISE);
    rows.push({ t, dow, hour, pickups });
  }
  return rows;
}

/** Completion gate for section 3: cut baseline RMSE by at least this percent. */
export const GAIN_GATE_PCT = 30;

export type DatetimeFeatureId = "hourBuckets" | "isWeekend" | "weekdayIndex" | "bucketWeekend";

export const DATETIME_FEATURE_ORDER: readonly DatetimeFeatureId[] = [
  "hourBuckets",
  "isWeekend",
  "weekdayIndex",
  "bucketWeekend",
];

export interface DatetimeFeatureMeta {
  id: DatetimeFeatureId;
  label: string;
  columns: number;
  tagline: string;
}

export const DATETIME_FEATURE_META: Record<DatetimeFeatureId, DatetimeFeatureMeta> = {
  hourBuckets: {
    id: "hourBuckets",
    label: "Hour-of-day buckets",
    columns: 3,
    tagline: "Night, morning, afternoon, evening as one-hot columns (night is the baseline).",
  },
  isWeekend: {
    id: "isWeekend",
    label: "Is-weekend flag",
    columns: 1,
    tagline: "One binary column: Saturday or Sunday.",
  },
  weekdayIndex: {
    id: "weekdayIndex",
    label: "Weekday as a number (0 to 6)",
    columns: 1,
    tagline: "Treats Monday to Sunday as a scale. Demand is not linear in that scale, so expect little.",
  },
  bucketWeekend: {
    id: "bucketWeekend",
    label: "Bucket x weekend interaction",
    columns: 3,
    tagline: "Lets weekends reshape the daily curve instead of just shifting it.",
  },
};

export const BUCKET_LABELS = ["Night (0-5)", "Morning (6-11)", "Afternoon (12-17)", "Evening (18-23)"] as const;

export function bucketOf(hour: number): number {
  return Math.floor(hour / 6);
}

/**
 * Design matrix for the pickups model. The baseline is [1, t]: an intercept
 * plus the raw hours-since-start timestamp, which is all you have before
 * extraction. Each enabled feature appends its columns.
 */
export function buildDatetimeMatrix(
  rows: readonly HourRow[],
  features: ReadonlySet<DatetimeFeatureId>
): number[][] {
  return rows.map((r) => {
    const row: number[] = [1, r.t];
    if (features.has("hourBuckets")) {
      const b = bucketOf(r.hour);
      row.push(b === 1 ? 1 : 0, b === 2 ? 1 : 0, b === 3 ? 1 : 0);
    }
    if (features.has("isWeekend")) {
      row.push(r.dow >= 5 ? 1 : 0);
    }
    if (features.has("weekdayIndex")) {
      row.push(r.dow);
    }
    if (features.has("bucketWeekend")) {
      const b = bucketOf(r.hour);
      const w = r.dow >= 5 ? 1 : 0;
      row.push(b === 1 ? w : 0, b === 2 ? w : 0, b === 3 ? w : 0);
    }
    return row;
  });
}

export function computeDatetimeFit(
  rows: readonly HourRow[],
  features: ReadonlySet<DatetimeFeatureId>
): FitResult {
  const fit = leastSquares(
    buildDatetimeMatrix(rows, features),
    rows.map((r) => r.pickups)
  );
  if (!fit) {
    throw new Error("Normal equations unexpectedly singular on the fixed hourly dataset");
  }
  return fit;
}
